services:
  move-ride-matching:
    image: nodejs
    container_name: move-ride-matching
    restart: always
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - move-ride-matching-network

networks:
  move-ride-matching-network:
    driver: bridge
    name: move-ride-matching-network

volumes:
  node_modules:
