name: CI/CD Pipeline to ECR and EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for GitHub Actions
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to ECR from GitHub Actions
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build and Push Docker image to ECR
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/move-ride-matching:latest

      # 5. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Create environment file from single secret
            cat > .env.development << 'EOF'
            ${{ secrets.ENV }}
            EOF
            
            # Login to ECR from EC2
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            
            # Pull latest image from ECR
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/move-ride-matching:latest
            
            # Stop and remove old container
            sudo docker stop move-ride-matching || true
            sudo docker rm move-ride-matching || true
            
            # Run new container with environment file
            sudo docker run -d -p 8001:8001 \
              --env-file .env.development \
              --name move-ride-matching \
              ${{ steps.login-ecr.outputs.registry }}/move-ride-matching:latest